import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

part 'household_repository.g.dart';

@riverpod
HouseholdRepository householdRepository(HouseholdRepositoryRef ref) {
  return HouseholdRepository(Supabase.instance.client);
}

class HouseholdRepository {
  final SupabaseClient _client;

  HouseholdRepository(this._client);

  // Create a new household
  Future<String> createHousehold(String name) async {
    final user = _client.auth.currentUser;
    if (user == null) throw Exception("User not logged in");

    // 1. Create Household Unit
    // Note: 'id' is generated by default gen_random_uuid() in DB if omitted,
    // but we need it returned.
    final response = await _client
        .from('household_unit')
        .insert({
          'name': name,
          'created_by': user.id,
        })
        .select('id')
        .single();

    final householdId = response['id'] as String;

    // 2. Update User Profile to join this household
    await _client.from('profiles').update({
      'household_id': householdId,
      'household_joined_at': DateTime.now().toIso8601String(),
    }).eq('id', user.id);

    return householdId;
  }

  // Join an existing household by ID (Code)
  Future<void> joinHousehold(String householdId) async {
    final user = _client.auth.currentUser;
    if (user == null) throw Exception("User not logged in");

    // Call Secure RPC
    await _client.rpc('join_household', params: {
      'target_household_id': householdId,
    });
  }

  // Leave current household
  Future<void> leaveHousehold() async {
    final user = _client.auth.currentUser;
    if (user == null) throw Exception("User not logged in");

    await _client.from('profiles').update({
      'household_id': null,
      'household_joined_at': null,
    }).eq('id', user.id);
  }

  // Delete Household (Owner Only)
  Future<void> deleteHousehold(String householdId) async {
    final user = _client.auth.currentUser;
    if (user == null) throw Exception("User not logged in");

    // Call Secure RPC to delete (handles kicking out members implicitly via DB update)
    await _client.rpc('delete_household', params: {
      'target_household_id': householdId,
    });

    // UI will update automatically via Realtime Stream in controller
  }

  // Get Household Details
  Future<Map<String, dynamic>?> getHousehold(String householdId) async {
    return await _client
        .from('household_unit')
        .select()
        .eq('id', householdId)
        .maybeSingle();
  }

  // Get Member Count (Optional)

  // Get Current User's Household
  Future<Map<String, dynamic>?> getMyHousehold() async {
    final user = _client.auth.currentUser;
    if (user == null) return null;

    // 1. Get Profile
    final profile = await _client
        .from('profiles')
        .select('household_id')
        .eq('id', user.id)
        .single();
    final householdId = profile['household_id'];

    if (householdId == null) return null;

    // 2. Get Household
    return await getHousehold(householdId);
  }

  // Get Members Stream
  Stream<List<Map<String, dynamic>>> getMembersStream(String householdId) {
    return _client
        .from('profiles')
        .stream(primaryKey: ['id'])
        .eq('household_id', householdId)
        .map((data) => data);
  }
}
